### ISSUE TITLE
Timing issues with bindx and SET_PEER_PRIMARY_ADDR

### ISSUE THREAD

**Issue by legion47T** [sctplab/usrsctp#57]
**Scenario**: SCTP connection fully established; v6 one-to-many sockets on both sides; one v4 and one v6 address in association on server's side, one v4 address on client's side; sending data is possible in both directions

If I add the client's v6 address, let the program `sleep()` for around 5 seconds and then call `SET_PEER_PRIMARY_ADDR`, everything works as intended.
If I add the client's v6 address and do **not** let the program `sleep()` (long enough), but instead call `SET_PEER_PRIMARY_ADDR` immediately, only the `ADD_ADDR` succeeds while the `SET_PEER_PRIMARY_ADDR` fails silently on the server's side.

**Alleged reason**: usrsctp sends a `SET_PEER_PRIMARY_ADDR` command out considerably faster than an `SCTP_BINDX_ADD_ADDR`. E.g. usrsctp sent the `SCTP_BINDX_ADD_ADDR` 1.5 seconds after `SET_PEER_PRIMARY_ADDR`.

**Debug output client side**:
```
*adding addresses*
Ok laddr->ifa:0x21bcd10 is possible, v6 addAddress returned
*set peer primary address*
asconf_queue_mgmt: appended asconf SET_PRIM_ADDR: IPv6 address: abcd::dcba:port:0 scope:0
set_primary_ip_address_sa: queued on tcb=0x21bdf90, IPv6 address: abcd::dcba:port:0 scope:1501644365
asconf_queue_mgmt: inserted asconf ADD_IP_ADDRESS: IPv6 address: abcd::dcba:port:0 scope:0
```
(note: not the actual address; `*foo*`: my own output)

Both `ASCONF`'s get acknowledged, so without involving the upper layer I can not know explicitly, whether the calls succeeded or failed.
I can only guess implicitly, when the server won't use the address as intended.

The SCTP implementation could keep track of `ADD/REM_ADDR`s calls and giving some kind of notification to the upper layer when the ACK arrives.
One could wait with `SET_PEER_PRIMARY_ADDR` for that notification.
Perhaps a dedicated error cause could also help in the long term.

Is there an intended or optimal way to handle these timing issues when adding or removing addresses or setting the peer's primary address?

I hope I have stated the issue clear enough. 
I can add more debug output, pcap's and/or my source code if necessary, though source code could take some time.

Thank you for looking into it!

**Comment by tuexen** [comment]
So when you call on the client side:
```
sctp_bindx(fd, IPv6address, 1, SCTP_BINDX_ADD_ADDR);
setsockopt(fd, IPPROTO_SCTP, SCTP_SET_PEER_PRIMARY_ADDR, IPv6address, sizeof(sctp_setpeerprim));
```
it fails, if you call
```
sctp_bindx(fd, IPv6address, 1, SCTP_BINDX_ADD_ADDR);
sleep(5);
setsockopt(fd, IPPROTO_SCTP, SCTP_SET_PEER_PRIMARY_ADDR, IPv6address, sizeof(sctp_setpeerprim));
```
is succeeds. Can you provide a .pcapng file which covers the association setup and the above time?
I would like to understand what is going on first.

**Comment by legion47T** [comment]
I attached my current test run:
Connection setup is initiated through a sendv, afterwards I send a 500B block of test data.
I wait 5 seconds 'til setup is done, then execute the commands as in your first example.
[2016-03-02_client.zip](https://github.com/sctplab/usrsctp/files/154397/2016-03-02_client.zip)

**Comment by tuexen** [comment]
Thanks for the trace. I confirm that there are problems. Let me debug this. I'll also need to figure out if this is a generic problem or limited to the userland stack. Once I have some fixes, I'll ask you for retesting. It might take a couple of days.

**Comment by legion47T** [comment]
Thank you, I look forward to it!

**Comment by tuexen** [comment]
I fixed one issue in https://github.com/sctplab/usrsctp/commit/7a9ea9f53e63af4613f355ac19b7208874029971. Can you retest and let me know if it fixes the issue also for the userland stack, since I tested the fix only with the FreeBSD kernel stack.

**Comment by legion47T** [comment]
The problem still exists for me.
I attached a new pcapng, though it doesn't really differ from the first.
Interestingly there is a correct Error Cause Indication in the ASCONF_ACK (which I overlooked the first time), but it seem like it is not acted upon by the SCTP stack. At least not in a way that the upper layer can check besides querying the primary address.
[2016-03-10_client.zip](https://github.com/sctplab/usrsctp/files/167327/2016-03-10_client.zip)

**Comment by tuexen** [comment]
OK. There might be also an issue with the iterator thread in the userland stack. Could you provide your test program to reproduce the issue with the userland stack?

**Comment by legion47T** [comment]
I'll try to upload it till tomorrow, I just need to work backwards through the objects and leave out the unimportant parts.

**Comment by tuexen** [comment]
OK. Great. Don't hurry. I'm not sure when I can work on it...

**Comment by legion47T** [comment]
This test program shows the same issue than my original code.
[testcode.zip](https://github.com/sctplab/usrsctp/files/168918/testcode.zip)

**Comment by tuexen** [comment]
OK. I fixed some bugs. However, there is one thing to deal with: The addition of addresses initiated by sctp_bindx() triggers a thread actually doing the work. So directly setting the peer primary after that results in a race. Therefore I'm now checking in the SCTP_SET_PEER_PRIMARY_ADDR socket option if the address has already been added. If not, an error is returned. This avoids sending the message to the peer in the wrong order. However, the application has to check the return code of the setsockopt() and need to retry later. Not perfect, but that is what can be done without major changes.
The bugs where:
* Not sending out queued ASCONF chunks when none is outstanding anymore
* Restricting address when they are added to the endpoint and honoring this in the SCTP_SET_PEER_PRIMARY_ADDR socket option.

Please retest.

**Comment by legion47T** [comment]
Thanks, I expect I can check it on Wednesday.
The fixes sound reasonable and I assume it will work fine.

**Comment by tuexen** [comment]
Great. Let me know how testing works. If it fixes your problem, close this issue.

**Comment by legion47T** [comment]
Testing worked great, one can easily let the program check for setsockopt() returning negative.
From my point of view this issue is fixed, thanks!
